import JsonLd from '../JsonLd'

export default function OrganisationJsonLd() {
  return (
    <JsonLd
      data={{
        '@context': 'https://schema.org',
        '@graph': [
          {
            '@type': 'Organization',
            '@id': 'https://stealthcyber.io/#organization',
            name: 'Stealth Cyber',
            legalName: 'Stealth Cyber Pty Ltd',
            url: 'https://stealthcyber.io',
            logo: 'https://stealthcyber.io/Primary-Reversed-Dark.png',
            image: 'https://stealthcyber.io/Primary-Reversed-Dark.png',
            description: 'Global cybersecurity consultancy and managed security service provider (MSSP) specialising in MDR, SOC operations, penetration testing, Essential Eight compliance, CMMC, ISO 27001, AI security, AI red teaming, and incident response for businesses across Australia, the Americas, and worldwide.',
            slogan: 'One Breach Can Change Everything. Don\'t Let It.',
            telephone: '+61752308381',
            foundingDate: '2024',
            foundingLocation: {
              '@type': 'Place',
              name: 'Gold Coast, Queensland, Australia',
            },
            numberOfEmployees: { '@type': 'QuantitativeValue', minValue: 10, maxValue: 50 },
            taxID: '72 675 840 632',
            contactPoint: [
              {
                '@type': 'ContactPoint',
                telephone: '+61752308381',
                contactType: 'sales',
                areaServed: [
                  { '@type': 'Country', name: 'Australia' },
                  { '@type': 'State', name: 'Queensland' },
                  { '@type': 'City', name: 'Gold Coast' },
                  { '@type': 'City', name: 'Brisbane' },
                ],
                availableLanguage: 'English',
              },
              {
                '@type': 'ContactPoint',
                telephone: '+18557742595',
                contactType: 'sales',
                areaServed: [
                  { '@type': 'Country', name: 'United States' },
                  { '@type': 'Country', name: 'Brazil' },
                  { '@type': 'Country', name: 'Canada' },
                ],
                availableLanguage: ['English', 'Portuguese', 'Spanish'],
              },
            ],
            address: [
              {
                '@type': 'PostalAddress',
                addressLocality: 'Gold Coast',
                addressRegion: 'QLD',
                addressCountry: 'AU',
              },
              {
                '@type': 'PostalAddress',
                addressLocality: 'S\u00e3o Paulo',
                addressRegion: 'SP',
                addressCountry: 'BR',
              },
              {
                '@type': 'PostalAddress',
                addressRegion: 'TX',
                addressCountry: 'US',
              },
            ],
            areaServed: [
              { '@type': 'Country', name: 'Australia' },
              { '@type': 'Country', name: 'United States' },
              { '@type': 'Country', name: 'Brazil' },
              { '@type': 'State', name: 'Queensland' },
              { '@type': 'City', name: 'Gold Coast' },
              { '@type': 'City', name: 'Brisbane' },
            ],
            sameAs: [
              'https://www.linkedin.com/company/stealthcyber',
            ],
            knowsAbout: [
              'Managed Detection and Response',
              'Security Operations Centre',
              'Penetration Testing',
              'Essential Eight',
              'Incident Response',
              'Digital Forensics',
              'CMMC Certification',
              'ISO 27001',
              'ISO 42001 AI Management',
              'AI Security',
              'AI Red Teaming',
              'AIUC-1',
              'Microsoft Sentinel',
              'Cyber Security Awareness Training',
              'GRC Compliance',
              'MSSP',
            ],
            hasCredential: [
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'CISSP - Certified Information Systems Security Professional' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'CISM - Certified Information Security Manager' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'OSCP - Offensive Security Certified Professional' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'OSWP - Offensive Security Wireless Professional' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'CEDP - Certified Exploit Development Professional' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'ISO 27001 Lead Implementer / Lead Auditor' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'ISO 42001 Lead Auditor - AI Management Systems' },
              { '@type': 'EducationalOccupationalCredential', credentialCategory: 'certification', name: 'CMMC Certified Assessor (CCA)' },
            ],
            hasOfferCatalog: {
              '@type': 'OfferCatalog',
              name: 'Cybersecurity Services',
              itemListElement: [
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Managed Detection & Response', url: 'https://stealthcyber.io/services#mdr' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Incident Response', url: 'https://stealthcyber.io/services#incident-response' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Essential Eight Compliance', url: 'https://stealthcyber.io/services#essential-eight' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'CMMC Assessment', url: 'https://stealthcyber.io/services#cmmc' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'ISO 27001', url: 'https://stealthcyber.io/services#iso27001' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'AI Security', url: 'https://stealthcyber.io/services#ai-security' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'AI Management Systems', url: 'https://stealthcyber.io/services#ai-management' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'AI Red Teaming', url: 'https://stealthcyber.io/services/ai#ai-red-teaming' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'AI Red Team Training', url: 'https://stealthcyber.io/services/ai#ai-red-team-training' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'GRC & Compliance', url: 'https://stealthcyber.io/services#grc' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Managed Security Services', url: 'https://stealthcyber.io/services#mss' } },
                { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Penetration Testing', url: 'https://stealthcyber.io/services#pentest' } },
              ],
            },
          },
          {
            '@type': 'LocalBusiness',
            '@id': 'https://stealthcyber.io/#localbusiness',
            name: 'Stealth Cyber',
            image: 'https://stealthcyber.io/Primary-Reversed-Dark.png',
            priceRange: '$$',
            url: 'https://stealthcyber.io',
            telephone: '+61752308381',
            address: {
              '@type': 'PostalAddress',
              addressLocality: 'Gold Coast',
              addressRegion: 'QLD',
              postalCode: '4217',
              addressCountry: 'AU',
            },
            geo: {
              '@type': 'GeoCoordinates',
              latitude: -28.0167,
              longitude: 153.4000,
            },
            openingHoursSpecification: {
              '@type': 'OpeningHoursSpecification',
              dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
              opens: '00:00',
              closes: '23:59',
            },
          },
          {
            '@type': 'ProfessionalService',
            name: 'Managed Detection and Response (MDR)',
            provider: { '@id': 'https://stealthcyber.io/#organization' },
            description: '24/7 managed detection and response service for businesses using continuous SOC monitoring, threat intelligence, and rapid incident containment.',
            areaServed: ['AU', 'US', 'BR'],
            serviceType: 'Managed Security Service',
            url: 'https://stealthcyber.io/services#mdr',
          },
          {
            '@type': 'ProfessionalService',
            name: 'Penetration Testing',
            provider: { '@id': 'https://stealthcyber.io/#organization' },
            description: 'Offensive security and penetration testing services including web application testing, OWASP LLM Top 10, AI/LLM red teaming, network assessments, and social engineering for businesses.',
            areaServed: ['AU', 'US', 'BR'],
            serviceType: 'Cybersecurity Consulting',
            url: 'https://stealthcyber.io/services#pentest',
          },
          {
            '@type': 'ProfessionalService',
            name: 'Essential Eight Assessment and Compliance',
            provider: { '@id': 'https://stealthcyber.io/#organization' },
            description: 'Essential Eight maturity assessments and remediation for Australian businesses and government entities, delivered by certified cybersecurity specialists.',
            areaServed: 'AU',
            serviceType: 'GRC Compliance',
            url: 'https://stealthcyber.io/services#essential-eight',
          },
          {
            '@type': 'ProfessionalService',
            name: 'Incident Response',
            provider: { '@id': 'https://stealthcyber.io/#organization' },
            description: 'Cyber incident response and forensic investigation including ransomware, token theft, business email compromise, and data breach response. Available 24/7.',
            areaServed: ['AU', 'US', 'BR'],
            serviceType: 'Incident Response',
            url: 'https://stealthcyber.io/services#incident-response',
          },
          {
            '@type': 'ProfessionalService',
            name: 'AI Security and AI Red Teaming',
            provider: { '@id': 'https://stealthcyber.io/#organization' },
            description: 'AI security assessments, AI red teaming, AI management systems (ISO 42001), AI readiness assessments, and AI red team training. Testing aligned to AIUC-1 and OWASP LLM Top 10.',
            areaServed: ['AU', 'US', 'BR'],
            serviceType: 'AI Security',
            url: 'https://stealthcyber.io/services/ai',
          },
        ],
      }}
    />
  )
}
